#!/bin/bash

./autoget

echo "Compiler = $1"
if [ "$1" == "gcc" ] ; then
    export TARGET=x86_64-linux-gnu
    export HOST=x86_64-linux-gnu
    export CC=gcc
    export CXX=g++
elif [ "$1" == "clang" ] ; then
    export TARGET=x86_64-linux-gnu
    export HOST=x86_64-linux-gnu
    export CC=clang
    export CXX=clang++
elif [ "$1" == "arm" ] ; then
    export TARGET=armv7a-linux-eabi
    export HOST=x86_64-linux-gnu
    export CC=arm-linux-gnueabi-gcc
    export CXX=arm-linux-gnueabi-g++
elif [ "$1" == "arm-clang" ] ; then
    export TARGET=armv7a-linux-eabi
    export HOST=x86_64-linux-gnu
    export CC="clang -target $TARGET"
    export CXX="clang++ -target $TARGET"
else
    unset CC
    unset CXX
    unset TARGET
    unset HOST
fi

echo "CC=$CC"
echo "CXX=$CXX"
echo "TARGET=$TARGET"
echo "HOST=$HOST"

export BUILD_TYPE="debug"
if [ "$2" == "release" ] ; then
    export BUILD_TYPE="release"
fi
echo "BUILD_TYPE=$BUILD_TYPE"


#pushd tools/googletest
#cmake CMakeLists.txt
#make
#popd

#pushd tools/protobuf
#./build-linux.sh
#if [ ! -d linux ] ; then
#    tar -xzvf linux.tar.gz
#fi
#popd

#pushd tools/openssl
#if [ ! -d linux ] ; then
#    tar -xzvf linux.tar.gz
#fi
#popd

pushd microreactor
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/discoveryservice
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/metricatorapi
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/metricator
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/streetgangproto
echo Configuring: $PWD
./generatepb
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/streetgangapi
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/worldapi
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/worldserver
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/streetgangserver
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/streetgangclient
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/simplewebserver
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

pushd example/bouncer
echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
popd

echo Configuring: $PWD
aclocal
autoheader
automake --add-missing
autoconf
echo "./configure --build=$TARGET --host=$HOST --target=$TARGET"

if [ "$BUILD_TYPE" == "release" ] ; then
    ./configure --build=$TARGET --host=$HOST --target=$TARGET
else
    ./configure --build=$TARGET --host=$HOST --target=$TARGET 'CFLAGS=-O0 -g' 'CXXFLAGS=-O0 -g'
fi


make
make check

./example/bin/mkdist.sh

