#!/bin/bash

sudo apt update -y
sudo apt install g++ -y
sudo apt install automake -y
sudo apt install pkg-config -y
sudo apt install cmake -y
sudo apt install uuid-dev -y
sudo apt install openssl libssl-dev -y
sudo apt install libprotobuf-dev -y
sudo apt install protobuf-compiler -y

sudo apt install cmake libgtest-dev -y
pushd /usr/src/gtest
sudo cmake CMakeLists.txt
sudo make
sudo cp *.a /usr/lib/
popd
pushd /usr/src/gmock
sudo cmake CMakeLists.txt
sudo make
sudo cp *.a /usr/lib/
popd

