#%RAML 1.0
---
title: StreetGang API
baseUri: http://localhost/{version}
version: v1

/version:
    get:
        description: Get the version of the server
        headers: 
        body: 
        responses: 200